# Spring DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/projekty
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Validation or export of schema DDL to the database (create, create-drop, validate, update, none)
spring.jpa.hibernate.ddl-auto=update

# Logging JPA Queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Security
# HTTP authentication credentials
spring.security.user.name=admin
spring.security.user.password=admin


spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false

jwt.access-secret-key=LptgFkjgovjfvmzBkWDSSykWr8Lc1yII
jwt.access-token-validity-in-min=15
jwt.refresh-secret-key=jQvoBrDBbimGj0Ys2C2QCafvSj3wYzGV
jwt.refresh-token-validity-in-min=480

spring.threads.virtual.enabled=true